### ISSUE TITLE
Categories, Labels, Environment pages are not there in admin panel

### ISSUE THREAD

**Issue by mithunadhikari40** [atakanuludag/personal-blog-app#4]
Hi there, 
This is possibly the best open-source blog app out there. I tried cloning and running it, but I am facing some issues. While I am able to see the admin dashboard, I am not able to navigate to either of the Categories, Labels, and Environment pages. 
Namely, those routes are:
http://localhost:3000/admin/categories
http://localhost:3000/admin/tags
http://localhost:3000/admin/files

Whenever I try to go to those pages, I get a 404 error page. A screenshot is attached for your reference. Also inside, app/.app/server/admin, I only see article.js, login.js, and setting.js. I suppose that is the issue.
Other pages in the admin dashboard are working fine, for e.g Dashboard, Settings

I see that there are API endpoints for those routes. However, it is challenging to manage those things via API and I would really appreciate it if you could take some time to push the fixes. I am hoping for your positive feedback.

![Screenshot from 2022-05-22 21-53-13](https://user-images.githubusercontent.com/16093696/169705053-dc161d4d-9e3e-400d-af36-54f05d5d7147.png)

**Comment by atakanuludag** [comment]
**Hi @mithunadhikari40,**

There may be pages that are not working because the project is in beta. I'm already working on the dev branch currently.
I add new updates to the project whenever I have time.
Many thanks for your interest and support :)

**Comment by mithunadhikari40** [comment]
Thank you so much. Will be waiting for your fix.

**Comment by atakanuludag** [comment]
> Thank you so much. Will be waiting for your fix.

Geç cevap gönderdiğim için özür dilerim. Tüm hatalar giderildi :)
